export type Product = {
  id: string;
  slug: string;
  name: string;
  price: number;
  description: string;
  image: string;
  sizes: string[];
  sportTags: string[];
  tribeTags: string[];
  categoryTags: string[];
  isNew: boolean;
  isFeatured: boolean;
};

export const products: Product[] = [
  {
    id: "p01",
    slug: "black-core-training-tee",
    name: "Black Core Training Tee",
    price: 42,
    description: "Lightweight knit for high-output sessions.",
    image: "/images/products/p01/main.jpg",
    sizes: ["S", "M", "L", "XL"],
    sportTags: ["gym", "running"],
    tribeTags: ["spartan", "samurai"],
    categoryTags: ["tops"],
    isNew: true,
    isFeatured: true
  },
  {
    id: "p02",
    slug: "maasai-endurance-singlet",
    name: "Maasai Endurance Singlet",
    price: 36,
    description: "Breathable knit engineered for heat.",
    image: "/images/products/p02/main.jpg",
    sizes: ["XS", "S", "M", "L"],
    sportTags: ["running", "triathlon"],
    tribeTags: ["maasai"],
    categoryTags: ["tops"],
    isNew: true,
    isFeatured: false
  },
  {
    id: "p03",
    slug: "samurai-seamless-baselayer",
    name: "Samurai Seamless Baselayer",
    price: 58,
    description: "Second-skin fit with sweat-mapped zones.",
    image: "/images/products/p03/main.jpg",
    sizes: ["S", "M", "L", "XL", "XXL"],
    sportTags: ["gym", "cycling"],
    tribeTags: ["samurai"],
    categoryTags: ["tops"],
    isNew: false,
    isFeatured: true
  },
  {
    id: "p04",
    slug: "viking-thermal-run-longsleeve",
    name: "Viking Thermal Run Longsleeve",
    price: 72,
    description: "Thermal grid knit for cold miles.",
    image: "/images/products/p04/main.jpg",
    sizes: ["S", "M", "L", "XL"],
    sportTags: ["running", "trail"],
    tribeTags: ["viking"],
    categoryTags: ["tops"],
    isNew: true,
    isFeatured: true
  },
  {
    id: "p05",
    slug: "spartan-interval-shorts",
    name: "Spartan Interval Shorts",
    price: 48,
    description: "Mobility-first cut with compression liner.",
    image: "/images/products/p05/main.jpg",
    sizes: ["S", "M", "L", "XL"],
    sportTags: ["gym", "running"],
    tribeTags: ["spartan"],
    categoryTags: ["bottoms", "shorts"],
    isNew: false,
    isFeatured: true
  },
  {
    id: "p06",
    slug: "maori-trail-shell",
    name: "Maori Trail Shell",
    price: 110,
    description: "Storm-ready shell for alpine sessions.",
    image: "/images/products/p06/main.jpg",
    sizes: ["M", "L", "XL"],
    sportTags: ["trail", "cycling"],
    tribeTags: ["maori"],
    categoryTags: ["outerwear"],
    isNew: true,
    isFeatured: true
  },
  {
    id: "p07",
    slug: "inca-altitude-tights",
    name: "Inca Altitude Tights",
    price: 84,
    description: "Thermal compression for climbs.",
    image: "/images/products/p07/main.jpg",
    sizes: ["S", "M", "L", "XL"],
    sportTags: ["trail", "running"],
    tribeTags: ["inca"],
    categoryTags: ["bottoms", "leggings"],
    isNew: false,
    isFeatured: false
  },
  {
    id: "p08",
    slug: "spartan-core-hoodie",
    name: "Spartan Core Hoodie",
    price: 90,
    description: "Heavyweight fleece for recovery days.",
    image: "/images/products/p08/main.jpg",
    sizes: ["M", "L", "XL", "XXL"],
    sportTags: ["gym"],
    tribeTags: ["spartan"],
    categoryTags: ["outerwear"],
    isNew: false,
    isFeatured: true
  },
  {
    id: "p09",
    slug: "samurai-precision-legging",
    name: "Samurai Precision Legging",
    price: 70,
    description: "High compression legging for speed work.",
    image: "/images/products/p09/main.jpg",
    sizes: ["XS", "S", "M", "L"],
    sportTags: ["running", "triathlon"],
    tribeTags: ["samurai"],
    categoryTags: ["bottoms", "leggings"],
    isNew: true,
    isFeatured: false
  },
  {
    id: "p10",
    slug: "viking-storm-bib",
    name: "Viking Storm Bib",
    price: 96,
    description: "Cycling bib designed for harsh conditions.",
    image: "/images/products/p10/main.jpg",
    sizes: ["S", "M", "L"],
    sportTags: ["cycling"],
    tribeTags: ["viking"],
    categoryTags: ["bottoms"],
    isNew: false,
    isFeatured: false
  },
  {
    id: "p11",
    slug: "maasai-sprint-short",
    name: "Maasai Sprint Short",
    price: 44,
    description: "Split hem short for hot intervals.",
    image: "/images/products/p11/main.jpg",
    sizes: ["XS", "S", "M", "L"],
    sportTags: ["running"],
    tribeTags: ["maasai"],
    categoryTags: ["bottoms", "shorts"],
    isNew: true,
    isFeatured: true
  },
  {
    id: "p12",
    slug: "maori-tide-swim-jammer",
    name: "Maori Tide Swim Jammer",
    price: 38,
    description: "Chlorine-ready compression swimwear.",
    image: "/images/products/p12/main.jpg",
    sizes: ["S", "M", "L"],
    sportTags: ["swimming", "triathlon"],
    tribeTags: ["maori"],
    categoryTags: ["bottoms"],
    isNew: false,
    isFeatured: false
  },
  {
    id: "p13",
    slug: "inca-thermal-half-zip",
    name: "Inca Thermal Half-Zip",
    price: 78,
    description: "Warmth-first midlayer for altitude sessions.",
    image: "/images/products/p13/main.jpg",
    sizes: ["S", "M", "L", "XL"],
    sportTags: ["trail", "running"],
    tribeTags: ["inca"],
    categoryTags: ["tops"],
    isNew: false,
    isFeatured: false
  },
  {
    id: "p14",
    slug: "spartan-iron-compression-top",
    name: "Spartan Iron Compression Top",
    price: 64,
    description: "Supportive compression for heavy sessions.",
    image: "/images/products/p14/main.jpg",
    sizes: ["S", "M", "L", "XL"],
    sportTags: ["gym"],
    tribeTags: ["spartan"],
    categoryTags: ["tops"],
    isNew: false,
    isFeatured: true
  },
  {
    id: "p15",
    slug: "samurai-rapid-cycle-jersey",
    name: "Samurai Rapid Cycle Jersey",
    price: 88,
    description: "Aero fit with bonded seams.",
    image: "/images/products/p15/main.jpg",
    sizes: ["S", "M", "L"],
    sportTags: ["cycling"],
    tribeTags: ["samurai"],
    categoryTags: ["tops"],
    isNew: true,
    isFeatured: false
  },
  {
    id: "p16",
    slug: "viking-endure-shell",
    name: "Viking Endure Shell",
    price: 105,
    description: "Windproof trail shell with matte finish.",
    image: "/images/products/p16/main.jpg",
    sizes: ["M", "L", "XL"],
    sportTags: ["trail"],
    tribeTags: ["viking"],
    categoryTags: ["outerwear"],
    isNew: false,
    isFeatured: true
  },
  {
    id: "p17",
    slug: "maasai-flow-tee",
    name: "Maasai Flow Tee",
    price: 32,
    description: "Ultra-light knit for fast reps.",
    image: "/images/products/p17/main.jpg",
    sizes: ["XS", "S", "M", "L", "XL"],
    sportTags: ["gym", "running"],
    tribeTags: ["maasai"],
    categoryTags: ["tops"],
    isNew: true,
    isFeatured: false
  },
  {
    id: "p18",
    slug: "maori-tactical-sports-bra",
    name: "Maori Tactical Sports Bra",
    price: 52,
    description: "High support, sculpted compression.",
    image: "/images/products/p18/main.jpg",
    sizes: ["XS", "S", "M", "L"],
    sportTags: ["gym", "running"],
    tribeTags: ["maori"],
    categoryTags: ["tops"],
    isNew: true,
    isFeatured: true
  },
  {
    id: "p19",
    slug: "inca-summit-vest",
    name: "Inca Summit Vest",
    price: 86,
    description: "Packable insulation for elevation shifts.",
    image: "/images/products/p19/main.jpg",
    sizes: ["S", "M", "L", "XL"],
    sportTags: ["trail"],
    tribeTags: ["inca"],
    categoryTags: ["outerwear"],
    isNew: false,
    isFeatured: true
  },
  {
    id: "p20",
    slug: "spartan-studio-jogger",
    name: "Spartan Studio Jogger",
    price: 68,
    description: "Structured jogger with tapered fit.",
    image: "/images/products/p20/main.jpg",
    sizes: ["S", "M", "L", "XL", "XXL"],
    sportTags: ["gym"],
    tribeTags: ["spartan"],
    categoryTags: ["bottoms"],
    isNew: false,
    isFeatured: false
  },
  {
    id: "p21",
    slug: "samurai-form-tank",
    name: "Samurai Form Tank",
    price: 34,
    description: "Racerback tank for heat control.",
    image: "/images/products/p21/main.jpg",
    sizes: ["XS", "S", "M", "L"],
    sportTags: ["gym", "running"],
    tribeTags: ["samurai"],
    categoryTags: ["tops"],
    isNew: false,
    isFeatured: false
  },
  {
    id: "p22",
    slug: "viking-core-thermal-tight",
    name: "Viking Core Thermal Tight",
    price: 82,
    description: "Thermal compression for winter runs.",
    image: "/images/products/p22/main.jpg",
    sizes: ["S", "M", "L", "XL"],
    sportTags: ["running", "trail"],
    tribeTags: ["viking"],
    categoryTags: ["bottoms", "leggings"],
    isNew: true,
    isFeatured: false
  },
  {
    id: "p23",
    slug: "maasai-tempo-crop",
    name: "Maasai Tempo Crop",
    price: 46,
    description: "Crop top with bonded hem.",
    image: "/images/products/p23/main.jpg",
    sizes: ["XS", "S", "M", "L"],
    sportTags: ["running", "gym"],
    tribeTags: ["maasai"],
    categoryTags: ["tops"],
    isNew: false,
    isFeatured: true
  },
  {
    id: "p24",
    slug: "maori-current-swim-suit",
    name: "Maori Current Swim Suit",
    price: 62,
    description: "Streamlined one-piece for open water.",
    image: "/images/products/p24/main.jpg",
    sizes: ["XS", "S", "M", "L"],
    sportTags: ["swimming", "triathlon"],
    tribeTags: ["maori"],
    categoryTags: ["tops", "bottoms"],
    isNew: true,
    isFeatured: false
  },
  {
    id: "p25",
    slug: "inca-ridge-knit",
    name: "Inca Ridge Knit",
    price: 74,
    description: "Structured knit with matte finish.",
    image: "/images/products/p25/main.jpg",
    sizes: ["S", "M", "L", "XL"],
    sportTags: ["gym", "trail"],
    tribeTags: ["inca"],
    categoryTags: ["tops"],
    isNew: true,
    isFeatured: true
  },
  {
    id: "p26",
    slug: "spartan-velocity-tank",
    name: "Spartan Velocity Tank",
    price: 30,
    description: "Lightweight tank with raw edge.",
    image: "/images/products/p26/main.jpg",
    sizes: ["S", "M", "L", "XL"],
    sportTags: ["gym", "running"],
    tribeTags: ["spartan"],
    categoryTags: ["tops"],
    isNew: false,
    isFeatured: false
  },
  {
    id: "p27",
    slug: "samurai-circuit-shorts",
    name: "Samurai Circuit Shorts",
    price: 50,
    description: "Run-ready short with bonded pockets.",
    image: "/images/products/p27/main.jpg",
    sizes: ["S", "M", "L"],
    sportTags: ["running", "gym"],
    tribeTags: ["samurai"],
    categoryTags: ["bottoms", "shorts"],
    isNew: false,
    isFeatured: true
  },
  {
    id: "p28",
    slug: "viking-field-sweatshirt",
    name: "Viking Field Sweatshirt",
    price: 76,
    description: "Structured crew for warm-ups.",
    image: "/images/products/p28/main.jpg",
    sizes: ["M", "L", "XL", "XXL"],
    sportTags: ["gym"],
    tribeTags: ["viking"],
    categoryTags: ["outerwear"],
    isNew: false,
    isFeatured: false
  },
  {
    id: "p29",
    slug: "maasai-pulse-tight",
    name: "Maasai Pulse Tight",
    price: 66,
    description: "Multi-sport tight with compressive knit.",
    image: "/images/products/p29/main.jpg",
    sizes: ["XS", "S", "M", "L"],
    sportTags: ["triathlon", "running"],
    tribeTags: ["maasai"],
    categoryTags: ["bottoms", "leggings"],
    isNew: true,
    isFeatured: false
  },
  {
    id: "p30",
    slug: "maori-reef-goggle",
    name: "Maori Reef Goggle",
    price: 28,
    description: "Low-profile goggle with anti-fog lenses.",
    image: "/images/products/p30/main.jpg",
    sizes: ["M"],
    sportTags: ["swimming"],
    tribeTags: ["maori"],
    categoryTags: ["accessories"],
    isNew: false,
    isFeatured: false
  }
];
